# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "CRUISE @ UNSW"
title: "Collaborative Human-Centric AI Systems (CRUISE)"
description: "Collaborative Human-Centric AI Systems (CRUISE) Lab, led by Prof. Flora Salim, works on machine learning for time-series, spatio-temporal data, and multimodal sensor data, and on trustworthy AI for decision making systems."

# URL
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Highlighter
highlighter: rouge

# Navigation
nav:
  - name: "home"
    href: "/"
  - name: "about"
    href: "/about"
  - name: projects
    href: "/projects"
  - name: "publications"
    href: "/publications"
  - name: "talks"
    href: "/talks"
  - name: "people"
    href: "/people"
  # - name: "Brick By Brick"
  #   href: /bbb.html
  - name: "<i class='fa fa-github'></i>"
    href: https://github.com/CRUISEResearchGroup
  - name: "ðŸ¤—"
    href: https://huggingface.co/CRUISEResearchGroup

# Sass
sass:
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "profile"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
